services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "80:80"
    links:
      - "php:php"
    volumes:
      - "./web:/var/keebsocial"
  php:
    build:
      context: .
      dockerfile: php/Dockerfile
    ports:
      - "9000:9000"
    links:
      - "db:db"
    environment:
      PHP_ROOT: "/var/keebsocial" # No trailing slash. Used for PHP includes.
      PHP_DEBUG: 'true'
    volumes:
      - "./web:/var/keebsocial"
  db:
    build:
      context: .
      dockerfile: mongodb/Dockerfile
    ports:
      - "27017:27017"
    volumes:
      - "./db:/data/db"